# Generated by Django 5.2.3 on 2025-06-16 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_category'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticet',
            new_name='Tickets',
        ),
    ]
